export const category_options = [
  { value: "software-engineer", label: "Software Engineer" },
  { value: "product-manager", label: "Product Manager" },
  { value: "data-scientist", label: "Data Scientist" },
  { value: "designer", label: "Designer" },
  { value: "marketing", label: "Marketing" },
  { value: "sales", label: "Sales" },
  { value: "hr", label: "Human Resources" },
  { value: "finance", label: "Finance" },
  { value: "operations", label: "Operations" },
  { value: "it-support", label: "IT Support / Helpdesk" },
  { value: "cloud", label: "Cloud (AWS/GCP/Azure)" },
  { value: "backend", label: "Backend Engineer" },
  { value: "frontend", label: "Frontend Developer" },
  { value: "fullstack", label: "Full-stack Developer" },
  { value: "devops", label: "DevOps / Platform" },
  { value: "qa", label: "QA / Test Engineer" },
  { value: "mobile", label: "Mobile Developer" },
  { value: "data-analyst", label: "Data Analyst" },
  { value: "data-engineer", label: "Data Engineer" },
  { value: "ai-ml", label: "AI / ML" },
  { value: "security", label: "Security / SecOps" },
  { value: "network", label: "Network Engineer" },
  { value: "sysadmin", label: "System Administrator" },
  { value: "database", label: "Database / DBA" },
  { value: "ui-ux", label: "UI/UX Designer" },
  { value: "product-designer", label: "Product Designer" },
  { value: "game-dev", label: "Game Developer" },
  { value: "embedded", label: "Embedded / IoT" },
  { value: "other", label: "Other" }
];

export const location_options = [
    { value: "remote", label: "Remote" },
    { value: "bangkok", label: "Bangkok" },
    { value: "chiang-mai", label: "Chiang Mai" },
    { value: "chiang-rai", label: "Chiang Rai" },
    { value: "lampang", label: "Lampang" },
    { value: "lamphun", label: "Lamphun" },
    { value: "mae-hong-son", label: "Mae Hong Son" },
    { value: "nakhon-sawan", label: "Nakhon Sawan" },
    { value: "nan", label: "Nan" },
    { value: "phayao", label: "Phayao" },
    { value: "phetchabun", label: "Phetchabun" },
    { value: "phichit", label: "Phichit" },
    { value: "phitsanulok", label: "Phitsanulok" },
    { value: "phrae", label: "Phrae" },
    { value: "sukhothai", label: "Sukhothai" },
    { value: "tak", label: "Tak" },
    { value: "uthai-thani", label: "Uthai Thani" },
    { value: "uttaradit", label: "Uttaradit" },
    { value: "chumphon", label: "Chumphon" },
    { value: "krabi", label: "Krabi" },
    { value: "nakhon-si-thammarat", label: "Nakhon Si Thammarat" },
    { value: "narathiwat", label: "Narathiwat" },
    { value: "pattani", label: "Pattani" },
    { value: "phang-nga", label: "Phang Nga" },
    { value: "phatthalung", label: "Phatthalung" },
    { value: "phuket", label: "Phuket" },
    { value: "ranong", label: "Ranong" },
    { value: "satun", label: "Satun" },
    { value: "songkhla", label: "Songkhla" },
    { value: "surat-thani", label: "Surat Thani" },
    { value: "trang", label: "Trang" },
    { value: "yala", label: "Yala" },
    { value: "chachoengsao", label: "Chachoengsao" },
    { value: "chanthaburi", label: "Chanthaburi" },
    { value: "chonburi", label: "Chonburi" },
    { value: "prachinburi", label: "Prachinburi" },
    { value: "rayong", label: "Rayong" },
    { value: "sa-kaeo", label: "Sa Kaeo" },
    { value: "trat", label: "Trat" },
    { value: "amnat-charoen", label: "Amnat Charoen" },
    { value: "bueng-kan", label: "Bueng Kan" },
    { value: "buriram", label: "Buriram" },
    { value: "chaiyaphum", label: "Chaiyaphum" },
    { value: "kalasin", label: "Kalasin" },
    { value: "khon-kaen", label: "Khon Kaen" },
    { value: "loei", label: "Loei" },
    { value: "maha-sarakham", label: "Maha Sarakham" },
    { value: "mukdahan", label: "Mukdahan" },
    { value: "nakhon-phanom", label: "Nakhon Phanom" },
    { value: "nakhon-ratchasima", label: "Nakhon Ratchasima" },
    { value: "nong-bua-lamphu", label: "Nong Bua Lamphu" },
    { value: "nong-khai", label: "Nong Khai" },
    { value: "roi-et", label: "Roi Et" },
    { value: "sakon-nakhon", label: "Sakon Nakhon" },
    { value: "sisaket", label: "Sisaket" },
    { value: "surin", label: "Surin" },
    { value: "ubon-ratchathani", label: "Ubon Ratchathani" },
    { value: "udon-thani", label: "Udon Thani" },
    { value: "yasothon", label: "Yasothon" }
];
