# Generated by Django 5.1 on 2025-08-17 15:09

import django.core.validators
import django.db.models.deletion
import jobs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('contacts', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('position', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('onsite', models.BooleanField(default=False, help_text='True if onsite, False if remote')),
                ('salary', models.IntegerField(help_text='Salary in your local currency')),
                ('min_year', models.IntegerField(help_text='Minimum years of experience required')),
                ('requirement', models.TextField(help_text='Job requirements and qualifications')),
                ('description', models.TextField(help_text='Detailed job description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='jobs.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name', max_length=200)),
                ('nick_name', models.CharField(blank=True, help_text='Preferred nickname', max_length=30, null=True)),
                ('pronoun', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.PositiveSmallIntegerField(help_text='Age in years', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(100)])),
                ('year', models.PositiveSmallIntegerField()),
                ('ku_generation', models.PositiveSmallIntegerField()),
                ('faculty', models.CharField(max_length=100)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('about_me', models.TextField(blank=True, help_text='Tell us about yourself')),
                ('email', models.EmailField(help_text='Contact email address', max_length=254)),
                ('cv', models.FileField(blank=True, help_text='Upload your CV (PDF recommended)', null=True, upload_to=jobs.models.student_file_upload_path)),
                ('resume', models.FileField(blank=True, help_text='Upload your resume (PDF recommended)', null=True, upload_to=jobs.models.student_file_upload_path)),
                ('transcript', models.FileField(blank=True, help_text='Upload your academic transcript (PDF recommended)', null=True, upload_to=jobs.models.student_file_upload_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
