# Generated by Django 5.2.5 on 2025-08-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('remote', 'Remote'), ('bangkok', 'Bangkok'), ('chiang-mai', 'Chiang Mai'), ('chiang-rai', 'Chiang Rai'), ('lampang', 'Lampang'), ('lamphun', 'Lamphun'), ('mae-hong-son', 'Mae Hong Son'), ('nakhon-sawan', 'Nakhon Sawan'), ('nan', 'Nan'), ('phayao', 'Phayao'), ('phetchabun', 'Phetchabun'), ('phichit', 'Phichit'), ('phitsanulok', 'Phitsanulok'), ('phrae', 'Phrae'), ('sukhothai', 'Sukhothai'), ('tak', 'Tak'), ('uthai-thani', 'Uthai Thani'), ('uttaradit', 'Uttaradit'), ('chumphon', 'Chumphon'), ('krabi', 'Krabi'), ('nakhon-si-thammarat', 'Nakhon Si Thammarat'), ('narathiwat', 'Narathiwat'), ('pattani', 'Pattani'), ('phang-nga', 'Phang Nga'), ('phatthalung', 'Phatthalung'), ('phuket', 'Phuket'), ('ranong', 'Ranong'), ('satun', 'Satun'), ('songkhla', 'Songkhla'), ('surat-thani', 'Surat Thani'), ('trang', 'Trang'), ('yala', 'Yala'), ('chachoengsao', 'Chachoengsao'), ('chanthaburi', 'Chanthaburi'), ('chonburi', 'Chonburi'), ('prachinburi', 'Prachinburi'), ('rayong', 'Rayong'), ('sa-kaeo', 'Sa Kaeo'), ('trat', 'Trat'), ('amnat-charoen', 'Amnat Charoen'), ('bueng-kan', 'Bueng Kan'), ('buriram', 'Buriram'), ('chaiyaphum', 'Chaiyaphum'), ('kalasin', 'Kalasin'), ('khon-kaen', 'Khon Kaen'), ('loei', 'Loei'), ('maha-sarakham', 'Maha Sarakham'), ('mukdahan', 'Mukdahan'), ('nakhon-phanom', 'Nakhon Phanom'), ('nakhon-ratchasima', 'Nakhon Ratchasima'), ('nong-bua-lamphu', 'Nong Bua Lamphu'), ('nong-khai', 'Nong Khai'), ('roi-et', 'Roi Et'), ('sakon-nakhon', 'Sakon Nakhon'), ('sisaket', 'Sisaket'), ('surin', 'Surin'), ('ubon-ratchathani', 'Ubon Ratchathani'), ('udon-thani', 'Udon Thani'), ('yasothon', 'Yasothon'), ('ang-thong', 'Ang Thong'), ('chai-nat', 'Chai Nat'), ('kanchanaburi', 'Kanchanaburi'), ('lopburi', 'Lopburi'), ('nakhon-nayok', 'Nakhon Nayok'), ('nakhon-pathom', 'Nakhon Pathom'), ('nonthaburi', 'Nonthaburi'), ('pathum-thani', 'Pathum Thani'), ('phra-nakhon-si-ayutthaya', 'Phra Nakhon Si Ayutthaya'), ('prachuap-khiri-khan', 'Prachuap Khiri Khan'), ('ratchaburi', 'Ratchaburi'), ('samut-prakan', 'Samut Prakan'), ('samut-sakhon', 'Samut Sakhon'), ('samut-songkhram', 'Samut Songkhram'), ('saraburi', 'Saraburi'), ('sing-buri', 'Sing Buri'), ('suphan-buri', 'Suphan Buri')], max_length=40),
        ),
    ]
