# Generated by Django 5.2.5 on 2025-09-09 01:58

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, help_text='KU student ID number', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=jobs.models.student_file_upload_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=jobs.models.student_file_upload_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to=jobs.models.student_file_upload_path),
        ),
    ]
