# Generated by Django 5.2.6 on 2025-09-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='short_description',
            new_name='description',
        ),
    ]
