# Generated by Django 5.2.5 on 2025-08-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_post_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='position',
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='work_field',
            field=models.CharField(choices=[('it-support', 'IT Support / Helpdesk'), ('cloud', 'Cloud (AWS/GCP/Azure)'), ('backend', 'Backend Engineer'), ('frontend', 'Frontend Developer'), ('fullstack', 'Full-stack Developer'), ('devops', 'DevOps / Platform'), ('qa', 'QA / Test Engineer'), ('mobile', 'Mobile Developer'), ('data-analyst', 'Data Analyst'), ('data-engineer', 'Data Engineer'), ('data-scientist', 'Data Scientist'), ('ai-ml', 'AI / ML'), ('security', 'Security / SecOps'), ('network', 'Network Engineer'), ('sysadmin', 'System Administrator'), ('database', 'Database / DBA'), ('ui-ux', 'UI/UX Designer'), ('product-designer', 'Product Designer'), ('game-dev', 'Game Developer'), ('embedded', 'Embedded / IoT'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(choices=[('bangkok', 'Bangkok'), ('chiang-mai', 'Chiang Mai'), ('chiang-rai', 'Chiang Rai'), ('lampang', 'Lampang'), ('lamphun', 'Lamphun'), ('mae-hong-son', 'Mae Hong Son'), ('nakhon-sawan', 'Nakhon Sawan'), ('nan', 'Nan'), ('phayao', 'Phayao'), ('phetchabun', 'Phetchabun'), ('phichit', 'Phichit'), ('phitsanulok', 'Phitsanulok'), ('phrae', 'Phrae'), ('sukhothai', 'Sukhothai'), ('tak', 'Tak'), ('uthai-thani', 'Uthai Thani'), ('uttaradit', 'Uttaradit'), ('chumphon', 'Chumphon'), ('krabi', 'Krabi'), ('nakhon-si-thammarat', 'Nakhon Si Thammarat'), ('narathiwat', 'Narathiwat'), ('pattani', 'Pattani'), ('phang-nga', 'Phang Nga'), ('phatthalung', 'Phatthalung'), ('phuket', 'Phuket'), ('ranong', 'Ranong'), ('satun', 'Satun'), ('songkhla', 'Songkhla'), ('surat-thani', 'Surat Thani'), ('trang', 'Trang'), ('yala', 'Yala'), ('chachoengsao', 'Chachoengsao'), ('chanthaburi', 'Chanthaburi'), ('chonburi', 'Chonburi'), ('prachinburi', 'Prachinburi'), ('rayong', 'Rayong'), ('sa-kaeo', 'Sa Kaeo'), ('trat', 'Trat'), ('amnat-charoen', 'Amnat Charoen'), ('bueng-kan', 'Bueng Kan'), ('buriram', 'Buriram'), ('chaiyaphum', 'Chaiyaphum'), ('kalasin', 'Kalasin'), ('khon-kaen', 'Khon Kaen'), ('loei', 'Loei'), ('maha-sarakham', 'Maha Sarakham'), ('mukdahan', 'Mukdahan'), ('nakhon-phanom', 'Nakhon Phanom'), ('nakhon-ratchasima', 'Nakhon Ratchasima'), ('nong-bua-lamphu', 'Nong Bua Lamphu'), ('nong-khai', 'Nong Khai'), ('roi-et', 'Roi Et'), ('sakon-nakhon', 'Sakon Nakhon'), ('sisaket', 'Sisaket'), ('surin', 'Surin'), ('ubon-ratchathani', 'Ubon Ratchathani'), ('udon-thani', 'Udon Thani'), ('yasothon', 'Yasothon'), ('ang-thong', 'Ang Thong'), ('chai-nat', 'Chai Nat'), ('kanchanaburi', 'Kanchanaburi'), ('lopburi', 'Lopburi'), ('nakhon-nayok', 'Nakhon Nayok'), ('nakhon-pathom', 'Nakhon Pathom'), ('nonthaburi', 'Nonthaburi'), ('pathum-thani', 'Pathum Thani'), ('phra-nakhon-si-ayutthaya', 'Phra Nakhon Si Ayutthaya'), ('prachuap-khiri-khan', 'Prachuap Khiri Khan'), ('ratchaburi', 'Ratchaburi'), ('samut-prakan', 'Samut Prakan'), ('samut-sakhon', 'Samut Sakhon'), ('samut-songkhram', 'Samut Songkhram'), ('saraburi', 'Saraburi'), ('sing-buri', 'Sing Buri'), ('suphan-buri', 'Suphan Buri')], max_length=40),
        ),
    ]
