# Generated by Django 5.2.6 on 2025-09-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_post_description_post_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='short_description',
            new_name='description',
        ),
    ]
