# Generated by Django 5.2.5 on 2025-08-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_post_position_post_image_url_post_work_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
