# Generated by Django 5.2.5 on 2025-09-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_student_name_student_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='about_me',
            field=models.TextField(blank=True, default='', help_text='Tell us about yourself'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ku_generation',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=3, help_text='KU student ID number', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
