# Generated by Django 5.2.5 on 2025-09-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_company_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='long_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
