# Generated by Django 5.2.5 on 2025-09-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_student_about_me_alter_student_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
