# Generated by Django 5.2.5 on 2025-09-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_company_is_approved_student_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='position',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
