# Generated by Django 5.2.5 on 2025-09-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_post_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='work_field',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
