# Generated by Django 5.2.5 on 2025-09-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_post_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='employment_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
